### PR TITLE
Heterogeneous Tiles

### LINKED ISSUE #539: RoCCExampleConfig Broken, undefined signal in FIRRTL
I haven't had a chance to debug it, but the `RoccExampleConfig` isn't getting through FIRRTL:

For completeness, this is using 9c0cc6fdf480efa18a2a4119e6a6e0dfa9235e8e.

```
cd emulator
make CONFIG=RoccExampleConfig

Exception in thread "main" firrtl.passes.PassExceptions: 
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 215:15:rocketchip.RoccExampleConfig.fir@133157.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 216:15:rocketchip.RoccExampleConfig.fir@133164.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 217:15:rocketchip.RoccExampleConfig.fir@133165.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 215:15:rocketchip.RoccExampleConfig.fir@133169.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 216:15:rocketchip.RoccExampleConfig.fir@133176.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 217:15:rocketchip.RoccExampleConfig.fir@133177.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 215:15:rocketchip.RoccExampleConfig.fir@133181.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Rocc.scala 89:54:rocketchip.RoccExampleConfig.fir@133186.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 215:15:rocketchip.RoccExampleConfig.fir@133225.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 216:15:rocketchip.RoccExampleConfig.fir@133232.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 217:15:rocketchip.RoccExampleConfig.fir@133233.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 215:15:rocketchip.RoccExampleConfig.fir@133237.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 216:15:rocketchip.RoccExampleConfig.fir@133244.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 217:15:rocketchip.RoccExampleConfig.fir@133245.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 215:15:rocketchip.RoccExampleConfig.fir@133249.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Rocc.scala 89:54:rocketchip.RoccExampleConfig.fir@133254.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 215:15:rocketchip.RoccExampleConfig.fir@133293.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 216:15:rocketchip.RoccExampleConfig.fir@133300.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 217:15:rocketchip.RoccExampleConfig.fir@133301.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 215:15:rocketchip.RoccExampleConfig.fir@133305.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 216:15:rocketchip.RoccExampleConfig.fir@133312.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 217:15:rocketchip.RoccExampleConfig.fir@133313.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 215:15:rocketchip.RoccExampleConfig.fir@133317.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Rocc.scala 89:54:rocketchip.RoccExampleConfig.fir@133322.4]: [module LegacyRoccComplex] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 216:15:rocketchip.RoccExampleConfig.fir@162093.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 217:15:rocketchip.RoccExampleConfig.fir@162094.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 215:15:rocketchip.RoccExampleConfig.fir@162098.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 216:15:rocketchip.RoccExampleConfig.fir@162105.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 217:15:rocketchip.RoccExampleConfig.fir@162106.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 215:15:rocketchip.RoccExampleConfig.fir@162110.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 216:15:rocketchip.RoccExampleConfig.fir@162117.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 217:15:rocketchip.RoccExampleConfig.fir@162118.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Rocc.scala 51:45:rocketchip.RoccExampleConfig.fir@162121.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 216:15:rocketchip.RoccExampleConfig.fir@162127.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 217:15:rocketchip.RoccExampleConfig.fir@162128.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 215:15:rocketchip.RoccExampleConfig.fir@162132.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 216:15:rocketchip.RoccExampleConfig.fir@162139.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 217:15:rocketchip.RoccExampleConfig.fir@162140.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 215:15:rocketchip.RoccExampleConfig.fir@162144.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 216:15:rocketchip.RoccExampleConfig.fir@162151.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 217:15:rocketchip.RoccExampleConfig.fir@162152.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Rocc.scala 51:45:rocketchip.RoccExampleConfig.fir@162155.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 216:15:rocketchip.RoccExampleConfig.fir@162161.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 217:15:rocketchip.RoccExampleConfig.fir@162162.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 215:15:rocketchip.RoccExampleConfig.fir@162166.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 216:15:rocketchip.RoccExampleConfig.fir@162173.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 217:15:rocketchip.RoccExampleConfig.fir@162174.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 215:15:rocketchip.RoccExampleConfig.fir@162178.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 216:15:rocketchip.RoccExampleConfig.fir@162185.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Bundles.scala 217:15:rocketchip.RoccExampleConfig.fir@162186.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.CheckChirrtl$UndeclaredReferenceException:  @[Rocc.scala 51:45:rocketchip.RoccExampleConfig.fir@162189.4]: [module RocketTile_l1tol2] Reference _T_177 is not declared.
firrtl.passes.PassException: 51 errors detected!
	at firrtl.passes.Errors.trigger(Passes.scala:29)
	at firrtl.passes.CheckChirrtl$.run(CheckChirrtl.scala:126)
	at firrtl.SimpleRun$$anonfun$runPasses$1$$anonfun$1.apply(Compiler.scala:115)
	at firrtl.SimpleRun$$anonfun$runPasses$1$$anonfun$1.apply(Compiler.scala:115)
	at firrtl.Utils$.time(Utils.scala:23)
	at firrtl.SimpleRun$$anonfun$runPasses$1.apply(Compiler.scala:115)
	at firrtl.SimpleRun$$anonfun$runPasses$1.apply(Compiler.scala:114)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at firrtl.SimpleRun$class.runPasses(Compiler.scala:114)
	at firrtl.PassBasedTransform.runPasses(Compiler.scala:132)
	at firrtl.PassBased$class.runPasses(Compiler.scala:128)
	at firrtl.PassBasedTransform.runPasses(Compiler.scala:132)
	at firrtl.PassBasedTransform.execute(Compiler.scala:136)
	at firrtl.Compiler$$anonfun$4$$anonfun$5.apply(Compiler.scala:251)
	at firrtl.Compiler$$anonfun$4$$anonfun$5.apply(Compiler.scala:251)
	at firrtl.Utils$.time(Utils.scala:23)
	at firrtl.Compiler$$anonfun$4.apply(Compiler.scala:251)
	at firrtl.Compiler$$anonfun$4.apply(Compiler.scala:250)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at firrtl.Compiler$class.compile(Compiler.scala:250)
	at firrtl.VerilogCompiler.compile(LoweringCompilers.scala:135)
	at firrtl.Driver$.execute(Driver.scala:143)
	at firrtl.Driver$.execute(Driver.scala:169)
	at firrtl.Driver$.main(Driver.scala:185)
	at firrtl.Driver.main(Driver.scala)
```

### PR DESCRIPTION
**Pull request by hcook**
This massive refactoring of the interior of the RocketTile (and some places beyond) makes it possible to elaborate heterogeneous Tiles, each with their own unique parameterization based on case classes.

* Added`tile` package: This package is intended to hold components re-usable across different types of tile. Will be the future location of TL2-RoCC accelerators and new diplomatic versions of intra-tile interfaces.
* Adopted `[ModuleName]Params` convention:  Code base was very inconsistent about what to name case classes that provide parameters to modules. Settled on calling them [ModuleName]Params to distinguish them from config.Parameters and config.Config. So far applied mostly only to case classes defined within `rocket` and `tile`.
* Defined `RocketTileParams`: A nested case class containing case classes for all the components of a tile (L1 caches and core). Allows all such parameters to vary per-tile.
* Defined `RocketCoreParams`: All the parameters that can be varied per-core.
* Defined `L1CacheParams`: A trait defining the parameters common to L1 caches, made concrete in different derived case classes.
* Defined `RocketTilesKey`: A sequence of `RocketTileParams`, one for every tile to be created.
* Provided `HeterogeneousDualCoreConfig`: An example of making a heterogeneous chip with two cores, one big and one little.
* Changes to legacy code: `ReplacementPolicy` moved to `package util`. `L1Metadata` moved to `package tile`. Legacy L2 cache agent removed because it can no longer share the metadata array implementation with the L1. Legacy GroundTests on life support.

Closes #539 #232 #450

### CODE REVIEW

File: src/main/scala/rocket/DCache.scala [hunk 1]
```diff
@@ -38,22 +38,19 @@ class DCacheDataArray(implicit p: Parameters) extends L1HellaCacheModule()(p) {
   }
 }
 
-class DCache(cfg: DCacheConfig, val scratch: () => Option[AddressSet] = () => None)(implicit p: Parameters) extends HellaCache(cfg)(p) {
+class DCache(val scratch: () => Option[AddressSet] = () => None)(implicit p: Parameters) extends HellaCache()(p) {
```
Comment (aswaterman) [inline src/main/scala/rocket/DCache.scala]: that's a mouthful

File: src/main/scala/rocket/BTB.scala [hunk 2]
```diff
@@ -16,7 +16,7 @@ case class BTBParams(
 
 trait HasBtbParameters extends HasCoreParameters {
   val btbParams = tileParams.btb.getOrElse(BTBParams(nEntries = 0))
-  val matchBits = pgIdxBits max log2Ceil(p(coreplex.CacheBlockBytes) * tileParams.icache.get.nSets)
+  val matchBits = pgIdxBits
```
Comment (aswaterman) [inline src/main/scala/rocket/BTB.scala]: Now that I look at this again, I can't understand why it would've mattered.  In this configuration, pgIdxBits and log2Ceil(p(coreplex.CacheBlockBytes) * tileParams.icache.get.nSets) should be equal.

Comment (hcook) [inline src/main/scala/rocket/BTB.scala]: yeah i agree, and it is still failing in the same way...

> C                   0:     443404 [1] pc=[008000297c] W[r 0=0000000000000000][0] R[r30=00000000800093f0] R[r13=00000000800093f0] inst=[fadf1ce3] bne     t5, a3, pc - 72
> C                   0:     443405 [1] pc=[0080002934] W[r14=0000000000000060][1] R[r15=0000000000000021] R[r31=00000000800093f3] inst=[03f7871b] addiw   a4, a5, 63
> C                   0:     443406 [1] pc=[0080002938] W[r14=0000006000000000][1] R[r14=0000000000000060] R[r 0=0000000000000000] inst=[02071713] slli    a4, a4, 32

File: src/main/scala/rocket/Rocket.scala [hunk 3]
```diff
@@ -324,9 +305,7 @@ class Rocket(val c: RocketConfig)(implicit p: Parameters) extends CoreModule()(p
   val mem_int_wdata = Mux(!mem_reg_xcpt && (mem_ctrl.jalr ^ mem_npc_misaligned), mem_br_target, mem_reg_wdata.asSInt).asUInt
   val mem_cfi = mem_ctrl.branch || mem_ctrl.jalr || mem_ctrl.jal
   val mem_cfi_taken = (mem_ctrl.branch && mem_br_taken) || mem_ctrl.jalr || (Bool(!fastJAL) && mem_ctrl.jal)
-  val mem_misprediction =
-    if (p(BtbKey).nEntries == 0) mem_cfi_taken
-    else mem_wrong_npc
+  val mem_misprediction = if (usingBTB) mem_cfi_taken else mem_wrong_npc
```
Comment (hcook) [inline src/main/scala/rocket/Rocket.scala]: @aswaterman found it! flipped this expression :(

Comment (aswaterman) [inline src/main/scala/rocket/Rocket.scala]: d'oh.
